name: Update & Deploy Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies (install Doxygen)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Step 3: Build the Doxygen documentation
    - name: Generate Doxygen Docs
      run: |
        pwd; ls
        # if gh-pages branch doesn't exist
        if [ `git rev-parse --verify gh-pages 2>/dev/null` ]
        then
          git checkout -b gh-pages
        else
          git checkout gh-pages
        fi

        # update .gitignore
        mv .github/.docs-gitignore .gitignore
        make docs  # Assuming your Makefile has a `docs` target to generate Doxygen output

    # Step 4: Create a new branch if it does not exist and commit the docs
    - name: Push to repository (gh-pages branch)
      run: |
        run: |
          git branch; git remote
          git config --global user.name "deependujha"
          git config --global user.email "deependujha21@gmail.com"
          git add .
          git commit -m "update docs"
          git push origin gh-pages

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Directory where your Doxygen docs are located
