name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies (install Doxygen)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Step 3: Build the Doxygen documentation
    - name: Generate Doxygen Docs
      run: |
        make docs  # Assuming your Makefile has a `docs` target to generate Doxygen output

    # Step 4: Create a new branch if it does not exist and commit the docs
    - name: Create or switch to gh-pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin gh-pages || true
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf . || true
        cp -r docs/html/* .  # Copy the generated Doxygen HTML to the root of the branch
        touch .nojekyll  # To ensure GitHub Pages treats files correctly
        git add .
        git commit -m "Update Doxygen docs" || echo "No changes to commit"
        git push origin gh-pages

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Directory where your Doxygen docs are located
