name: Update & Deploy Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies (install Doxygen)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Step 3: Build the Doxygen documentation
    - name: Generate Doxygen Docs
      run: |
        git checkout gh-pages \
        && mv .github/.docs-gitignore .gitignore \
        && make docs

    # Step 4: Create a new branch if it does not exist and commit the docs
    - name: Push to repository (gh-pages branch)
      run: |
        run: |
          git checkout gh-pages  \
          && git config --global user.name "deependujha" \
          && git config --global user.email "deependujha21@gmail.com" \
          && git add . \
          && git commit -m "update docs" \
          && git push -u origin main:gh-pages \

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Directory where your Doxygen docs are located
